-- Seed data: 8 blog posts (3 marked featured, to demonstrate the
-- carousel — 2+ featured posts auto-rotate on the blog page).
-- Safe to run once. Re-running will fail on the unique slug
-- constraint rather than silently duplicating rows.

insert into posts (title, slug, description, content, image, category, featured) values
('Why AI Video Still Needs a Human Editor', 'ai-video-still-needs-human-editor', 'Generation gets you 80% of the way there. The last 20% — pacing, rhythm, the cut that makes a scene land — is still a human job.', '<p>Every few months, a new model drops and someone declares editing dead. It isn''t, and the reason is simple: generation solves for footage, not for story. A model can give you a technically flawless shot of a product spinning under studio light. It cannot tell you that the shot is boring at second three and needs to cut a full second earlier than feels natural, because human attention doesn''t move at the pace a render does.</p>
<p>On every project that comes through the lab, the AI-generated or AI-assisted footage is maybe half the total effort. The other half is the same craft editors have always practiced: matching cuts to a beat, building tension through withheld information, knowing when a hold is confidence and when it''s just dead air. None of that comes from the model. It comes from watching the cut back forty times and trusting your gut on the forty-first.</p>
<h2>Where the leverage actually is</h2>
<p>The honest pitch for AI video isn''t "replace your editor." It''s "give your editor ten options instead of one, in the time it used to take to get one." A director used to burn a full day on a single b-roll setup. Now that day buys a dozen variations — different angles, different lighting moods, different pacing of camera movement — and the editor''s job shifts from generating options to curating them ruthlessly.</p>
<p>That''s a better job, not a smaller one. Curation at that volume is a real skill, and it''s the skill we hire for. Anyone can prompt a model. Knowing which of forty outputs actually serves the story is the part that doesn''t automate.</p>
<h2>What this means for a brief</h2>
<p>If you''re briefing an AI video project, the most useful thing you can hand over isn''t a shot list — it''s a reference cut. Show us the pacing you want, even if it''s from a competitor''s ad or a film you like. The generation step is fast enough now that iterating on options isn''t the bottleneck. Editorial judgment is, and that''s exactly where we spend the time you''re paying for.</p>', '', 'AI Video', true),
('Inside Our AI Agent Stack: What Actually Ships', 'inside-our-ai-agent-stack', 'Not every agent needs an LLM in the loop. Here''s the decision tree we actually use before writing a single prompt.', '<p>Clients come in asking for "an AI agent" the way they used to ask for "an app" — as a category, not a spec. Half the time, what they actually need is a well-built automation with no model in the loop at all: a form that routes to the right calendar, a webhook that syncs two tools, a scheduled job that checks a status and sends a Slack message. Building that as a chatbot would be slower to ship, more expensive to run, and less reliable than a deterministic workflow.</p>
<p>So the first thing we do on every agent engagement is figure out where judgment is actually required. If the task is "read this message and decide which of eight categories it belongs to, where the categories aren''t cleanly separable by keywords" — that''s a model problem. If the task is "when a form is submitted, create a record and notify someone" — that''s plumbing, and treating it as an AI problem just adds latency and cost for no benefit.</p>
<h2>The stack, roughly</h2>
<p>For the agents that do need a model: we default to a smaller, faster model for classification and routing, and only escalate to a larger model for the steps where reasoning quality actually changes the outcome — drafting a reply, handling an edge case, summarizing something long. Most of a conversation''s turns don''t need your best model. The one turn where the customer is annoyed and needs to be de-escalated well does.</p>
<p>Every agent we ship gets a fallback path to a human, not as an afterthought but as a designed state. An agent that can''t say "let me get someone for you" and mean it is a liability, not a feature. Voice agents especially — the cost of a bad handoff there is a lost customer, not just a bad chat transcript.</p>
<h2>What we actually measure</h2>
<p>Not "did the agent respond," but "did the resolution rate hold up once the novelty wore off." The first week of any agent deployment looks great because the queries are the easy, expected ones. Week four is when the weird inputs show up, and that''s the number we report back to clients — not the demo number.</p>', '', 'AI Agents', true),
('The Chamfered Corner: A Design System Retrospective', 'chamfered-corner-design-system-retrospective', 'Every button on this site has its corners cut at an angle instead of rounded. Here''s why that one decision shaped everything else.', '<p>Early on, we made a call that seems small but ended up load-bearing for the entire visual identity: no rounded corners, anywhere, on anything interactive. Buttons, tags, cards — everything gets a chamfered corner instead, a straight diagonal cut rather than a curve. It was a reaction to how much of the web had converged on the same soft, rounded, friendly-SaaS look, and we wanted something that read as engineered rather than approachable.</p>
<p>The chamfer does something rounded corners can''t: it implies a cut, a fabrication process, a physical object that was made rather than rendered. Paired with the monospace labels and the acid-green accent, it pushes the whole system toward "lab equipment" instead of "consumer app," which is exactly the read we wanted for a studio that positions itself as a production lab rather than an agency.</p>
<h2>Where it got hard</h2>
<p>Chamfered corners are trivial in CSS with a clip-path polygon. They get complicated the moment you need a border, a shadow, and a hover state that all respect the same cut corners without artifacts at the seams. We ended up standardizing on a single clip-path formula across every component so the angle is always identical — a small thing, but it''s the difference between a system that feels designed and one that feels approximated.</p>
<p>The other cost: chamfered corners actively fight with anything that wants to be circular — avatars, status dots, loading spinners. We didn''t fight that battle. Round things stay round. The system isn''t "no curves ever," it''s "no soft edges on things you click." That distinction did more to keep the identity coherent than any single color or font choice.</p>', '', 'Branding', false),
('UGC That Doesn''t Look Like UGC', 'ugc-that-doesnt-look-like-ugc', 'The best-performing AI-generated UGC we''ve shipped shares one trait: nobody clocks it as generated until we tell them.', '<p>There''s a specific uncanny signature to a lot of AI-generated UGC — too-perfect skin, eyes that don''t quite land on the product, a smile that holds a beat too long. It performs badly not because audiences consciously spot the tell, but because something about it registers as off before they can name it, and the ad gets scrolled past.</p>
<p>The fix isn''t a better model. It''s editorial restraint. The generations that actually convert are the ones we deliberately rough up afterward: a slight color grade to match a phone camera''s white balance, a touch of compression artifacting, a cut that includes the awkward half-second before someone starts talking. Real UGC is imperfect by nature. Polishing that imperfection out is what makes generated content read as fake.</p>
<h2>The brief that works</h2>
<p>When a client asks for "UGC-style" content, we push back on the instinct to make it look expensive. The entire value of the format is that it doesn''t look like an ad. If we''ve done our job, the finished piece should look like it was shot on a mid-range phone by someone with decent instincts, not by a production team — even though a production team, and a model, did in fact make it.</p>', '', 'AI Video', false),
('Voice Agents in 2026: What''s Actually Working', 'voice-agents-2026-whats-actually-working', 'Latency killed voice agents for years. That''s mostly solved now — which means the failures we see today are all judgment failures, not tech failures.', '<p>For a long time, the honest answer to "should we build a voice agent" was "not yet" — the round-trip latency between a caller finishing a sentence and the agent responding was long enough that every call felt like a bad international connection. That''s largely fixed now. Streaming transcription plus smaller, faster models for the turns that don''t need heavy reasoning has gotten response time down to something that feels close to a real conversation.</p>
<p>Which means the agents that fail today aren''t failing on tech. They''re failing on judgment: not recognizing when a caller is frustrated, not knowing when to stop trying to resolve something and just transfer, repeating a menu of options to someone who very clearly already told you what they want.</p>
<h2>The design pattern that matters most</h2>
<p>Every voice agent we build gets an explicit "confidence threshold" for handoff — not a vague instruction to "escalate difficult calls," but a concrete rule: if the caller has repeated themselves, if sentiment analysis flags frustration, or if the request falls outside a defined set of resolvable intents, hand off immediately, no third attempt at clarification. The agents that annoy people are the ones that keep trying to be helpful past the point where a human would have already said "let me grab someone for you."</p>
<p>The other lesson: give the agent a personality that matches the brand, but keep it short. Callers don''t want charm, they want their problem solved. The best-performing voice agents we''ve shipped say less per turn than early versions did, not more.</p>', '', 'AI Agents', true),
('Site Speed Is a Brand Decision', 'site-speed-is-a-brand-decision', 'A slow site doesn''t just lose conversions. It tells visitors, in the first two seconds, how much you actually cared about the details.', '<p>We treat load performance as a design constraint, not an engineering afterthought handled after launch. The reasoning is simple: a visitor forms an impression of craft before they''ve read a word of copy, purely from how the page feels to load and scroll. A site that stutters on first paint undercuts every other design decision made on the page, no matter how considered they were.</p>
<p>The usual culprits are boring and well-documented — unoptimized images, render-blocking third-party scripts, web fonts loaded without a fallback. What''s less talked about is how much damage a convenience tool can do once a site is live and content is being added and changed dynamically. A styling toolchain that recompiles itself in the browser on every DOM change is fine for a prototype and genuinely costly on a page that injects a nav bar, a footer, and dynamic content on every load — each injection can trigger a full re-scan, which adds up to real, felt lag, not just a worse Lighthouse score.</p>
<h2>What we actually check</h2>
<p>Before we call a build done, we look at what happens on first load with a cold cache, and — separately — what happens during normal interaction after the page has settled: scrolling, opening a menu, submitting a form. Slowness on the second kind is worse for trust than slowness on the first, because it reads as "this thing is fragile" rather than "this thing is loading."</p>', '', 'Web Dev', false),
('Editing at Volume Without Losing the Plot', 'editing-at-volume-without-losing-the-plot', 'Turning around thirty short-form cuts a week only works if the system, not the editor''s memory, is what enforces consistency.', '<p>The failure mode of high-volume editing isn''t quality on any single piece — it''s drift. Cut thirty short-form videos in a week and, without a system, the fifth one starts pacing differently from the first, the caption style wanders, the outro changes because someone forgot what the last version looked like. None of it is wrong in isolation. Together, it reads as inconsistent, and inconsistency is what makes a channel feel unmanaged.</p>
<p>The fix is unglamorous: a living style reference that''s actually enforced, not just written down once and ignored. Every cut gets checked against the same handful of rules — hook length, caption timing, where the logo bump lands — before it ships. It''s closer to a QA pass than an editorial one, and it''s the single biggest lever for making a channel feel like a channel instead of a pile of individually decent clips.</p>
<h2>Where AI actually helps here</h2>
<p>Not with the creative cut — with the repetitive parts around it. Auto-generating caption timing, flagging clips that run long against a platform''s optimal length, batching color matching across a week''s footage so it doesn''t have to be eyeballed from scratch each time. That''s where the volume gets absorbed. The actual edit — what stays, what goes, where the joke lands — is still done by hand, every time.</p>', '', 'Video Editing', false),
('Five Prompts We Rewrite Every Week', 'five-prompts-we-rewrite-every-week', 'A running list of the prompt patterns that reliably break, and what we''ve replaced them with after enough failed generations.', '<p>Most prompt-engineering advice ages badly because it''s tied to a specific model''s quirks at a specific point in time. What doesn''t age badly is the shape of the mistakes people make writing prompts for video generation specifically — and a handful of those show up on nearly every project, badly enough that we''ve rewritten our internal templates around avoiding them.</p>
<h2>Describing motion instead of describing a result</h2>
<p>"The camera slowly pans right" produces wildly inconsistent results across models. "A slow reveal of the product from left to right, ending centered in frame" produces something usable, because it describes the outcome rather than the mechanism. We stopped asking for camera moves and started asking for what the frame should contain at the end of the shot.</p>
<h2>Over-specifying lighting in words instead of reference</h2>
<p>Three adjectives for lighting ("moody, dramatic, cinematic") get you a different, incompatible result every time. One reference image gets you consistency. If a client''s brief has strong lighting language in it, we convert it to a reference frame before it ever reaches a prompt.</p>
<h2>Stacking too many instructions in one generation</h2>
<p>Asking for a specific action, a specific expression, and a specific background simultaneously reliably degrades all three. We generate in passes now — background and composition first, then refine the subject in a second pass — rather than trying to nail everything in one shot.</p>
<p>None of this is exotic. It''s mostly just the discipline of treating the model as a collaborator with real, learnable failure modes, instead of a magic box you describe things to once and hope for the best.</p>', '', 'AI Video', false);